event/urls.py
from django.urls import path
from . import views

""" match when url is [/event/]"""

app_name = 'event'

urlpatterns = [
    path('calendar/', views.CalendarRedirectView.as_view(), name='calendar_redirect'),
    path('calendar/<int:year>/<int:month>/', views.CalendarView.as_view(), name='calendar'),
    path('event_create/<int:year>/<int:month>/<int:day>/', views.EventCreateView.as_view(), name='event_create'),
    path('add_friend/<int:pk>/', views.add_friend, name='add_friend'),
    path('event_detail/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('event_update/<int:pk>', views.EventUpdateView.as_view(), name='event_update'),
    path('update_friend/<int:pk>/', views.update_friend, name='update_friend'),
    path('event_delete/<int:pk>', views.EventDeleteView.as_view(), name='event_delete'),
]

friend/urls.py
from django.urls import path
from . import views

""" match when url is [/]"""

app_name = 'friend'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('friend_list/', views.FriendListView.as_view(), name='friend_list'),
    path('friend_detail/<int:pk>/', views.FriendDetailView.as_view(), name='friend_detail'),
    path('friend_create/', views.FriendCreateView.as_view(), name='friend_create'),
    path('friend_update/<int:pk>/', views.FriendUpdateView.as_view(), name='friend_update'),
    path('friend_delete/<int:pk>/', views.FriendDeleteView.as_view(), name='friend_delete'),
    path('friend_event_list/<int:pk>/', views.FriendEventListView.as_view(), name='friend_event_list'),
]

event/models.py
from django.db import models
from django.contrib.auth.models import User
from friend.models import Friend

""" Model for Event """
class Event(models.Model):
    
    # Relationship between Event and User is "many to one"
    user = models.ForeignKey(
        to=User,
        verbose_name='User',
        on_delete=models.CASCADE
    )

    # Relationship between Event and Friend is "many to many"
    friend_name = models.ManyToManyField(
        to=Friend,
        blank=True,
    )

    event_name = models.CharField(
        verbose_name='Event Name',
        max_length=200
    )

    date = models.DateField(
        verbose_name='Date',
    )

    place = models.CharField(
        verbose_name='Place',
        max_length=200,
        blank=True,
        null=True
    )
    
    memo = models.TextField(
        verbose_name='Memo',
        max_length=500,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name_plural='Event'
    
    def __str__(self):
        return self.event_name

event/forms.py
from django import forms
import datetime
from .models import Event, Friend

""" Form for Event """
class EventForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ('event_name', 'place', 'memo')
 
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

""" Form for Selecting Year and Date """
class DateForm(forms.Form):

    date_now = datetime.datetime.now() # today's information

    # select year from [1990, 2030)
    years = tuple([(x, str(x)) for x in range(1990, 2030)]) 
    year = forms.ChoiceField(choices=years, initial=date_now.year)

    # select date from [1, 12]
    months = tuple([(x, str(x)) for x in range(1, 13)]) 
    month = forms.ChoiceField(choices=months, initial=date_now.month)




        


event/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
import datetime, calendar
from .models import Event, Friend
from .forms import EventForm, DateForm

""" View for Redirecting to Calendar with Today's Information """
class CalendarRedirectView(LoginRequiredMixin, generic.RedirectView):

    date_now = datetime.datetime.now() # today's information
    url = '/event/calendar/' + str(date_now.year) + '/' + str(date_now.month)

""" View for the Calendar """
class CalendarView(LoginRequiredMixin, generic.FormView):

    template_name = 'calendar.html'
    form_class = DateForm
    
    # making data for sending to html file
    def get_context_data(self, **kwargs):
        # get date from the url
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        # all dates in 2Darray
        weeks = calendar.monthcalendar(year, month) 
        # key:day value:all events of the day
        schedule_dic = {} 
        for week in weeks:
            for day in week:
                if day == 0:
                    continue
                schedule = Event.objects.filter(user=self.request.user, date=datetime.date(year, month, day))
                schedule_dic[day] = schedule
        # send data to html as a context
        context = super().get_context_data()
        context['weeks'] = weeks
        context['schedule_dic'] = schedule_dic
        # year and month of the specified date
        context['year'] = year
        context['month'] = month
        # previous month
        context['prev_year'] = year - 1 if month == 1 else year
        context['prev_month'] = month - 1 if month > 1 else 12
        # next month
        context['next_year'] = year + 1 if month == 12 else year
        context['next_month'] = month + 1 if month < 12 else 1
        # today's information
        date_now = datetime.datetime.now()
        context['today'] = date_now.day
        # flag Ture:this calendar includes today
        context['today_flag'] = False 
        if year == date_now.year and month == date_now.month:
            context['today_flag'] = True
        
        return context

    # redirect when date is specified by form and if the input is valid
    def form_valid(self, form):
        # get date from form
        year = form.data.get('year')
        month = form.data.get('month')
        # get the redirect path
        url = reverse_lazy('event:calendar', kwargs={'year': year, 'month': month})

        return redirect(url)
    
    # display error message if the input of the form is invalid
    def form_invalid(self, form):
        return super().form_invalid(form)

""" View for Creating Event """
class EventCreateView(LoginRequiredMixin, generic.CreateView):

    template_name = 'event_create.html'
    model = Event
    form_class = EventForm

    # save the data in database if the input of the form is valid
    def form_valid(self, form):
        event = form.save(commit=False)
        event.user = self.request.user # add user information
        # get the specified date from the url
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        event.date = datetime.date(year, month, day) # add date information
        event.save()
        # get the redirect path for adding friend information
        url = reverse_lazy('event:add_friend', kwargs={'pk': event.pk})

        return redirect(url)
    
    # display error message if the input of the form is invalid
    def form_invalid(self, form):
        return super().form_invalid(form)

""" View for Adding Friend Information """
@login_required
def add_friend(request, pk):
    user = request.user # get user information from http request
    event = Event.objects.get(pk=pk)
    # GET request : display the form
    if request.method == 'GET':
        # make choices to select friends
        friends = Friend.objects.filter(user=user).order_by('friend_name')
        # send the choice to the html file if some friends are registered
        if friends:
            context = {'friends': friends}
            return render(request, 'add_friend.html', context)
        # finish the process if no friends are registered
        else: 
            url = reverse_lazy('event:event_detail', kwargs={'pk': pk})
            return redirect(url)
    # POST request : save the friend information in database
    else:
        friends_id = request.POST.getlist("choice") # get the selected friends from the form
        for id in friends_id:
            event.friend_name.add(Friend.objects.get(id=int(id)))
        event.save()
        url = reverse_lazy('event:event_detail', kwargs={'pk': pk})
        return redirect(url)

""" View for Displaying the Detail of the Event """
class EventDetailView(LoginRequiredMixin, generic.DetailView):

    template_name = 'event_detail.html'
    model = Event
    context_object_name = 'event'

    # making data for sending to html file
    def get_context_data(self, **kwargs):
        # get primary key of the event from the url
        pk = self.kwargs.get('pk')
        context = super().get_context_data()
        # get the friends information of the event
        event = Event.objects.filter(pk=pk)
        friends = event[0].friend_name.all()
        context['friends_name'] = friends
        return context

""" View for Updating the Event """
class EventUpdateView(LoginRequiredMixin, generic.UpdateView):

    template_name = 'event_update.html'
    model = Event
    form_class = EventForm
    context_object_name = 'event'

    # determine the url redirect to when the input of the form is valid
    def get_success_url(self):
        return reverse_lazy('event:update_friend', 
        kwargs={'pk': self.kwargs['pk']})
    
    # redirect to the url if the input of the form is valid
    def form_valid(self, form):
        return super().form_valid(form)
    
    # display error message if the input of the form is invalid
    def form_invalid(self, form):
        return super().form_invalid(form)

""" View for Updating Friend Information of the Event """
@login_required
def update_friend(request, pk):
    # get the user information from the http request
    user = request.user
    # get the event informaion using the primary key from the url
    event = Event.objects.get(pk=pk)
    # GET request : display the form
    if request.method == 'GET':
        # make choices to select friends
        friends = Friend.objects.filter(user=user).order_by('friend_name')
        # send the choice to the html file if some friends are registered
        if friends:
            context = {'friends': friends}
            return render(request, 'add_friend.html', context)
        # finish the process if no friends are registered
        else: 
            url = reverse_lazy('event:event_detail', kwargs={'pk': pk})
            return redirect(url)
    # POST request : save the friend information in database
    else:
        friends_id = request.POST.getlist("choice") # get the selected friends from the form
        event.friend_name.clear() # delete once and choose from the beginning
        for id in friends_id:
            event.friend_name.add(Friend.objects.get(id=int(id)))
        event.save()
        url = reverse_lazy('event:event_detail', kwargs={'pk': pk})
        return redirect(url)

""" View for Deleting the Event """
class EventDeleteView(LoginRequiredMixin, generic.DeleteView):

    template_name = 'event_delete.html'
    model = Event
    success_url = reverse_lazy('event:calendar_redirect') # the url redirect to when the input of the form is valid
    context_object_name = 'event'

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

event/templates/add_friend.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="m-5">
<form method='POST'>
    {% csrf_token %}
    {% for friend in friends %}
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" name="choice" value={{ friend.pk }}>
        <label class="form-check-label" for="inlineCheckbox1">{{ friend.friend_name }}</label>
    </div>
    {% endfor %}
    <div class="option my-2">
        <button type='submit'>Add</button>
        <a href="{% url 'event:calendar_redirect' %}" class="mx-2">Cancel</a>
    </div>
</form>
</div>
{% endblock %}


event/templates/calendar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    table {
        table-layout: fixed;
    }

    td > div {
        height: 64px;
        overflow: auto;
        white-space: nowrap;
    }

    th > div {
        height: 12px;
    }
</style>
<div class="mt-1">
    <form method="POST">
    {% csrf_token %}
    {{ form.year }}年{{ form.month }}月<button type='submit' class="mx-1">表示</button>
    </form>
    <p class="text-center m-0">
        <a href="{% url 'event:calendar' prev_year prev_month %}">前月</a>
        <span class="mx-2" style="font-size: x-large;">{{ year }}年{{ month }}月</span>
        <a href="{% url 'event:calendar' next_year next_month %}">翌月</a>
    </p>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col"><div>Mon</div></th>
            <th scope="col"><div>Tue</div></th>
            <th scope="col"><div>Wed</div></th>
            <th scope="col"><div>Thu</div></th>
            <th scope="col"><div>Fri</div></th>
            <th scope="col"><div>Sat</div></th>
            <th scope="col"><div>Sun</div></th>
        </tr>
    </thead>
    <tbody>
        {% for week in weeks %}
            <tr>
            {% for day in week %}
                {% if today_flag and today == day %}
                    <td style="background-color: aliceblue;">
                {% else %}
                    <td>
                {% endif %}
                <div>
                    {% if day != 0 %}
                        <a href="{% url 'event:event_create' year month day %}">{{ day }}</a>
                    {% endif %}
                    {% for key, schedules in schedule_dic.items %}
                        {% if day == key %}
                            {% for schedule in schedules %}
                                <p><a href="{% url 'event:event_detail' pk=schedule.pk %}">{{ schedule }}</a></p>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>
                </td>
            {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

event/templates/event_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="m-5">
<form method='POST'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type='submit'>Create</button>
</form>
</div>
{% endblock %}


event/templates/event_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method='POST'>
    {% csrf_token %}
    <p>Really?</p>
    <button type='submit'>Delete</button>
    <a href="{% url 'event:event_detail' pk=event.pk %}">Cancel</a>
</form>
{% endblock %}

event/templates/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="mt-5 row">
    <div class="col-12 mt-3">
        <h3 class="text-left mt-2">{{ event.event_name }}</h3>
            <div class="ml-2">
            <p class="text-left mt-3">日時 : {{ event.date|date:"Y/n/j" }}</p>
            {% if event.place != None %}
            <p class="text-left mt-2">場所 : {{ event.place }}</p>
            {% endif %}
            <p class="text-left mt-2">友達 : 
                {% for friend_name in friends_name %}
                    <a href="{% url 'friend:friend_detail' pk=friend_name.pk %}">{{ friend_name }}　</a>
                {% endfor %}
            </p>
            <p class="text-left mt-2">メモ :</p>
            <p class="text-left mt-2 border">{{ event.memo | linebreaksbr}}</p>
        </div>
        <div class="form-group row justify-content-center">
            <div class="mr-1">
                <a href="{% url 'event:event_update' pk=event.pk %}" class="btn border py-0 border-dark rounded-0 font-weight-bold" style="background-color: #EEEEEE ;">Edit</a>
            </div>
            <div class="ml-1">
                <a href="{% url 'event:event_delete' pk=event.pk %}" class="btn border py-0 border-dark rounded-0 font-weight-bold" style="background-color: #EEEEEE ;">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

event/templates/event_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="m-5">
<form method='POST'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <div class="option my-2">
        <button type='submit'>Edit</button>
        <a href="{% url 'event:event_detail' pk=event.pk %}" class="mx-2">Cancel</a>
    </div>
</form>
</div>
{% endblock %}