accounts/urls.py
from django.urls import path
from . import views

""" match when url is [/login/]"""

app_name = 'accounts'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

event/urls.py
from django.urls import path
from . import views

""" match when url is [/event/]"""

app_name = 'event'

urlpatterns = [
    path('calendar/', views.CalendarRedirectView.as_view(), name='calendar_redirect'),
    path('calendar/<int:year>/<int:month>/', views.CalendarView.as_view(), name='calendar'),
    path('event_create/<int:year>/<int:month>/<int:day>/', views.EventCreateView.as_view(), name='event_create'),
    path('add_friend/<int:pk>/', views.add_friend, name='add_friend'),
    path('event_detail/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('event_update/<int:pk>', views.EventUpdateView.as_view(), name='event_update'),
    path('update_friend/<int:pk>/', views.update_friend, name='update_friend'),
    path('event_delete/<int:pk>', views.EventDeleteView.as_view(), name='event_delete'),
]

friend/urls.py
from django.urls import path
from . import views

""" match when url is [/]"""

app_name = 'friend'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('friend_list/', views.FriendListView.as_view(), name='friend_list'),
    path('friend_detail/<int:pk>/', views.FriendDetailView.as_view(), name='friend_detail'),
    path('friend_create/', views.FriendCreateView.as_view(), name='friend_create'),
    path('friend_update/<int:pk>/', views.FriendUpdateView.as_view(), name='friend_update'),
    path('friend_delete/<int:pk>/', views.FriendDeleteView.as_view(), name='friend_delete'),
    path('friend_event_list/<int:pk>/', views.FriendEventListView.as_view(), name='friend_event_list'),
]

friend/models.py
from django.db import models
from django.contrib.auth.models import User

""" Model for Friend """
class Friend(models.Model):

    # Relationship between Friend and User is "many to one"
    user = models.ForeignKey(
        to=User,
        verbose_name='User',
        on_delete=models.CASCADE
    )

    friend_name = models.CharField(
        verbose_name='Friend Name',
        max_length=200,
    )

    birth_day = models.DateField(
        verbose_name='Birth Day',
        blank=True,
        null=True
    )

    memo = models.TextField(
        verbose_name='Memo',
        max_length=500,
        blank=True,
        null=True
    )
    
    photo = models.ImageField(
        verbose_name='Photo',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name_plural='Friend'

    def __str__(self):
        return self.friend_name

friend/forms.py
from django import forms
from .models import Friend
import datetime

""" Form for Friend """
class FriendForm(forms.ModelForm):
   
    class Meta:
        model = Friend
        fields = ('friend_name', 'birth_day', 'memo', 'photo')
        widgets = {
            'birth_day': forms.SelectDateWidget(years=[x for x in range(1900, datetime.datetime.now().year + 1)])
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values(attrs={"type":"date"}):
                field.widget.attrs['class'] = 'form-control'

friend/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Friend
from .forms import FriendForm


""" View for the Index """
class IndexView(generic.TemplateView):

    template_name = 'index.html'

""" View for the Friend List """
class FriendListView(LoginRequiredMixin, generic.ListView):

    template_name = 'friend_list.html'
    context_object_name = 'friends'

    # making the data from database sending to the html file 
    def get_queryset(self):
        friends = Friend.objects.filter(user=self.request.user).order_by('friend_name')
        return friends
    
""" View for Displaying the Detail of the Event """
class FriendDetailView(LoginRequiredMixin, generic.DetailView):

    template_name = 'friend_detail.html'
    model = Friend
    context_object_name = 'friend'

    # making data for sending to html file
    def get_context_data(self, **kwargs):
        # get primary key of the friend and user information from the url
        pk = self.kwargs.get('pk')
        user = self.request.user
        context = super().get_context_data()
        # get the events information of the friend
        friend = Friend.objects.filter(pk=pk, user=user)
        events = friend[0].event_set.order_by('-date')
        context['last_5_events'] = events[:5] # last 5 events
        context['event_count'] = len(events) # the counts of played with the friend
        return context

""" View for Displaying List of the Event played with the Friend """
class FriendEventListView(LoginRequiredMixin, generic.TemplateView):

    template_name = 'friend_event_list.html'

    # making data for sending to html file
    def get_context_data(self, **kwargs):
        # get primary key of the friend and user information from the url
        pk = self.kwargs.get('pk')
        user = self.request.user
        context = super().get_context_data()
        # get the events information of the friend
        friend = Friend.objects.filter(pk=pk, user=user)
        events = friend[0].event_set.order_by('-date')
        context['events'] = events
        context['event_count'] = len(events) # the counts of played with the friend
        context['friend_name'] = friend[0].friend_name
        return context

""" View for Creating Friend """
class FriendCreateView(LoginRequiredMixin, generic.CreateView):

    template_name = 'friend_create.html'
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('friend:friend_list') # the url redirect to when the input of the form is valid

    # save the data in database if the input of the form is valid
    def form_valid(self, form):
        friend = form.save(commit=False)
        friend.user = self.request.user # add user information
        friend.save()
        return super().form_valid(form)
    
    # display error message if the input of the form is invalid
    def form_invalid(self, form):
        return super().form_invalid(form)

""" View for Updating the Friend """
class FriendUpdateView(LoginRequiredMixin, generic.UpdateView):

    template_name = 'friend_update.html'
    model = Friend
    form_class = FriendForm
    context_object_name = 'friend'

    # determine the url redirect to when the input of the form is valid
    def get_success_url(self):
        return reverse_lazy('friend:friend_detail', 
        kwargs={'pk': self.kwargs['pk']})
    
    # redirect to the url if the input of the form is valid
    def form_valid(self, form):
        return super().form_valid(form)
    
    # display error message if the input of the form is invalid
    def form_invalid(self, form):
        return super().form_invalid(form)
    
""" View for Deleting the Friend """
class FriendDeleteView(LoginRequiredMixin, generic.DeleteView):

    template_name = 'friend_delete.html'
    model = Friend
    success_url = reverse_lazy('friend:friend_list') # the url redirect to when the input of the form is valid
    context_object_name = 'friend'

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

friend/templates/friend_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="m-5">
<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type='submit'>Create</button>
</form>
</div>
{% endblock %}

friend/templates/friend_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method='POST'>
    {% csrf_token %}
    <p>Really?</p>
    <button type='submit'>Delete</button>
    <a href="{% url 'friend:friend_detail' pk=friend.pk %}">Cancel</a>
</form>
{% endblock %}

friend/templates/friend_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row m-5 px-5">
    <div class="col-12 col-lg-4">
        <!-- {% if friend.photo %}
        <img src="{{ friend.photo.url }}" class="img-fluid">
        {% else %}
        <img src="{% static 'img/icon.png' %}" class="img-fluid">
        {% endif %} -->
        <img src="{% static 'img/Man.png' %}" class="img-fluid">
    </div>
    <div class="col-12 col-lg-4 mt-3">
        <p>氏名　 : {{ friend.friend_name }}</p>
        {% if friend.birth_day %}
            <p>誕生日 : {{ friend.birth_day|date:"Y/n/j" }}</p>
        {% else %}
            <p>誕生日 : 未登録</p>
        {% endif %}
        <p>{{ friend.memo | linebreaksbr}}</p>
    </div>
    <div class="col-12 col-lg-4 mt-3">
        <p>遊んだ回数　 : {{ event_count }}</p>
        {% if event_count > 0 %}
        <p>最近のイベント</p>
        {% for event in last_5_events %}
        <p>{{ event.date|date:"Y/n/j" }}<a href="{% url 'event:event_detail' pk=event.pk %}"> {{ event }}</a></p>
        {% endfor %}
        <p><a href="{% url 'friend:friend_event_list' pk=friend.pk %}">全て表示</a></p>
        {% endif %}
    </div>
</div>
<div class="form-group row justify-content-center">
    <div class="mr-1">
        <a href="{% url 'friend:friend_update' pk=friend.pk %}" class="btn border py-0 border-dark rounded-0 font-weight-bold" style="background-color: #EEEEEE ;">Edit</a>
    </div>
    <div class="ml-1">
        <a href="{% url 'friend:friend_delete' pk=friend.pk %}" class="btn border py-0 border-dark rounded-0 font-weight-bold" style="background-color: #EEEEEE ;">Delete</a>
    </div>
</div>
{% endblock %}

friend/templates/friend_event_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row m-5 px-5">
    <div class="col-12 col-lg-4 mt-3">
        <p><strong>氏名</strong>　 : {{ friend_name }}</p>
        <p><strong>遊んだ回数</strong>　 : {{ event_count }}</p>
        {% if event_count > 0 %}
    </div>
    <div class="col-12 col-lg-4 mt-3">
        <p><strong>イベント一覧</strong></p>
        {% for event in events %}
        <p>{{ event.date|date:"Y/n/j" }}<a href="{% url 'event:event_detail' pk=event.pk %}"> {{ event }}</a></p>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

friend/templates/friend_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a href="{% url 'friend:friend_create' %}" class="btn border my-3 border-dark rounded-0 font-weight-bold" style="background-color: #EEEEEE ;">Add New Friend</a>
<div class="row my-3" style="background-color: white;">
    {% for friend in friends %}
    <div class="col-4 col-lg-2 border px-3 pt-3">
        <!-- {% if friend.photo %}
        <img src="{{ friend.photo.url }}" class="img-fluid">
        {% else %}
        <img src="{% static 'img/icon.png' %}" class="img-fluid">
        {% endif %} -->
        <img src="{% static 'img/Man.png' %}" class="img-fluid">
        <p class="text-left mt-2">氏名 　: {{ friend.friend_name }}</p>
        {% if friend.birth_day %}
            <p class="text-left">誕生日 : {{ friend.birth_day|date:"Y/n/j" }}</p>
        {% else %}
            <p class="text-left">誕生日 : 未登録</p>
        {% endif %}
        <p class="text-center">
            <a href="{% url 'friend:friend_detail' pk=friend.pk %}" class="btn border py-0 border-dark rounded-0" style="background-color: #EEEEEE ;">Detail</a>
        </p>
    </div>
    {% endfor %}
</div>
{% endblock %}


friend/templates/friend_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="m-5">
<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <div class="option my-2">
        <button type='submit'>Edit</button>
        <a href="{% url 'friend:friend_detail' pk=friend.pk %}" class="mx-2">Cancel</a>
    </div>
</form>
</div>
{% endblock %}


friend/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
      <h1 class="display-3">Friends Management</h1>
      <p>いつ誰とどこで遊んだか。</p>
      <p>この子とはどれくらい遊んだか。</p>
      <h4>すぐに思い出せますか？</h4>
    </div>
  </div>

  <div class="container">
    <div class="row">
      {% if not user.is_authenticated %}
      <div class="col-md-4">
        <h2><strong>Accounts</strong></h2>
        <p>初めての方は<a href="{% url 'accounts:signup' %}">Sign Up</a>からアカウントを作成してください。</p>
        <p>アカウントをお持ちの方は<a href="{% url 'accounts:login' %}">Log In</a>からログインしてください。</p>
      </div>
      {% else %}
      <div class="col-md-2"></div>
      {% endif %}
      <div class="col-md-4">
        <h2><strong>Friend List</strong></h2>
        <p>友達の一覧表示、詳細表示、追加、編集、削除が行えます。</p>
        <p><a class="btn btn-secondary" href="{% url 'friend:friend_list' %}" role="button">Friend List</a></p>
      </div>
      <div class="col-md-4">
        <h2><strong>Calendar</strong></h2>
        <p>イベント内容を記載したカレンダーの表示やイベントの追加、編集、削除などが行えます。</p>
        <p><a class="btn btn-secondary" href="{% url 'event:calendar_redirect' %}" role="button">Calendar</a></p>
      </div>
      
      
    </div>

    <hr>

  </div>
{% endblock %}