accounts/urls.py
from django.urls import path
from . import views

""" match when url is [/login/]"""

app_name = 'accounts'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

event/urls.py
from django.urls import path
from . import views

""" match when url is [/event/]"""

app_name = 'event'

urlpatterns = [
    path('calendar/', views.CalendarRedirectView.as_view(), name='calendar_redirect'),
    path('calendar/<int:year>/<int:month>/', views.CalendarView.as_view(), name='calendar'),
    path('event_create/<int:year>/<int:month>/<int:day>/', views.EventCreateView.as_view(), name='event_create'),
    path('add_friend/<int:pk>/', views.add_friend, name='add_friend'),
    path('event_detail/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('event_update/<int:pk>', views.EventUpdateView.as_view(), name='event_update'),
    path('update_friend/<int:pk>/', views.update_friend, name='update_friend'),
    path('event_delete/<int:pk>', views.EventDeleteView.as_view(), name='event_delete'),
]

friend/urls.py
from django.urls import path
from . import views

""" match when url is [/]"""

app_name = 'friend'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('friend_list/', views.FriendListView.as_view(), name='friend_list'),
    path('friend_detail/<int:pk>/', views.FriendDetailView.as_view(), name='friend_detail'),
    path('friend_create/', views.FriendCreateView.as_view(), name='friend_create'),
    path('friend_update/<int:pk>/', views.FriendUpdateView.as_view(), name='friend_update'),
    path('friend_delete/<int:pk>/', views.FriendDeleteView.as_view(), name='friend_delete'),
    path('friend_event_list/<int:pk>/', views.FriendEventListView.as_view(), name='friend_event_list'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friends Management</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/friends_management.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'friend:index' %}">Friends Management</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'friend:index' %}">Home</a>
                </li>
                <!-- Login -->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'friend:friend_list' %}">Friend List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'event:calendar_redirect' %}">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                <!-- Not Login -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main class="mb-auto">
        <div class="container">
            {% block content %}
            {% endblock %} 
        </div>
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>